export const BOT_REPLIES: { [key: string]: string[] } = {
  'hallo': ['Hallo! 👋', 'Hey! Schön, dass du da bist! 😄', 'Hi! Wie geht’s dir?'],
  'hi': ['Hi! 😄', 'Hey! 👋', 'Hallo!'],
  'hey': ['Hey! Wie läuft’s?', 'Hallo! 😃', 'Hi! Schön, dass du da bist.'],
  'wie geht': ['Mir geht es gut, danke! 😊', 'Alles bestens hier! 😎', 'Super, danke der Nachfrage!'],
  'was machst du': ['Ich chatte gerade mit dir! 😄', 'Ich warte auf deine Nachricht!', 'Nichts Besonderes, nur quatschen.'],
  'hilfe': ['Wie kann ich dir helfen?', 'Was möchtest du wissen?', 'Frag mich alles, ich versuche zu antworten.'],
  'witz': ['Warum können Geister so schlecht lügen? 👻 Weil sie so leicht durchschaubar sind 😄', 'Ich kenne einen guten Witz über Programmierer… 😄', 'Treffen sich zwei Planeten… keiner lacht. 😅'],
  'tschüss': ['Tschüss! Bis bald! 👋', 'Auf Wiedersehen! 😊', 'Mach’s gut!'],
  'guten morgen': ['Guten Morgen! ☀️', 'Morgen! Hoffe, du hattest einen guten Start!', 'Hallo! Schön, dass du da bist.'],
  'gute nacht': ['Gute Nacht! 🌙', 'Schlaf gut! 😴', 'Träum was Schönes!'],
  'wetter': ['Ich bin kein Wetterfrosch, aber hoffentlich scheint die Sonne!', 'Frag mich lieber nicht nach dem Wetter. 🌤️', 'Heute scheint es Chat-warm! 😉'],
  'wie spät ist es': ['Schau auf die Uhr, ich kann leider nicht die Zeit sehen ⏰', 'Es ist immer Zeit für einen Chat! 😄'],
  'wer bist du': ['Ich bin dein Chat-Bot 🤖', 'Ich bin hier, um mit dir zu plaudern!'],
  'was kannst du': ['Ich kann auf bestimmte Nachrichten antworten 😊', 'Ich bin ein kleiner Chat-Bot, aber sehr nett!'],
  'lustig': ['Ich liebe Witze! 😄', 'Lachen ist gesund! 😂', 'Hier ein kleiner Witz für dich: …'],
  'musik': ['Ich höre gerne alles, was du mir erzählst 🎵', 'Musik ist toll! Hast du einen Lieblingssong?'],
  'essen': ['Ich esse leider nicht, aber ich liebe Rezepte! 🍕', 'Hast du Hunger? 😋'],
  'sport': ['Sport ist wichtig! 💪', 'Ich kann nicht trainieren, aber motivieren! 😄'],
  'lieblingsfarbe': ['Ich liebe blau! 💙', 'Meine Lieblingsfarbe ist digital 😉', 'Ich mag alle Farben! 🌈'],
  'reise': ['Reisen klingt toll! 🌍', 'Wo würdest du gerne hinreisen?'],
  'schule': ['Schule kann manchmal stressig sein 😅', 'Was ist dein Lieblingsfach?'],
  'arbeit': ['Arbeit hält uns beschäftigt! 💼', 'Hoffentlich hast du einen guten Tag auf der Arbeit!'],
  'film': ['Filme sind toll! 🎬', 'Welches Genre magst du am liebsten?'],
  'buch': ['Lesen ist spannend! 📚', 'Hast du ein Lieblingsbuch?'],
  'tier': ['Ich liebe Katzen 😺 und Hunde 🐶!', 'Welches Tier magst du am liebsten?'],
  'liebe': ['Liebe ist etwas Schönes ❤️', 'Ich bin nur ein Bot, aber ich schicke dir Liebe! 💌'],
  'danke': ['Gern geschehen! 😄', 'Immer gerne! 👍', 'Kein Problem! 😊'],
  'bitte': ['Kein Problem! 😄', 'Gern geschehen!', 'Immer gerne!'],
  'ok': ['Alles klar! 😎', 'Okay! 👍', 'Verstanden!'],
  'super': ['Freut mich! 😄', 'Cool! 👍', 'Klasse!'],
  'verstehst du': ['Ich versuche mein Bestes! 😅', 'Ich glaube schon! 😉', 'Ein bisschen schon… 😄'],
  'bla': ['Hihi 😄', 'Interessant… 🤔', 'Kannst du das genauer erklären?'],
  '???': ['Ich bin mir nicht sicher, was du meinst 😅', 'Kannst du das anders formulieren?', 'Ich habe das nicht verstanden. 🤔'],
  'asdf': ['😂 Lustige Buchstabenfolge!', 'Hä? 😅', 'Kannst du das erklären?'],
  'nicht verstanden': ['Sorry, ich habe das nicht verstanden 😅', 'Kannst du das bitte anders schreiben?', 'Ich verstehe dich leider nicht. 🤔'],
  'random': ['Zufall! 🎲', 'Hmm… interessant 🤔', 'Ich weiß nicht, was ich dazu sagen soll.'],
  'alles klar': ['Alles klar! 😄', 'Super! 👍', 'Gut zu wissen!'],
  'keine ahnung': ['Kein Problem 😄', 'Alles gut, ich auch nicht 😅', 'Vielleicht können wir das später klären.'],
  'fragen': ['Frag mich was! 😊', 'Ich versuche zu antworten! 😎', 'Immer her mit deinen Fragen!']
};
