export const BOT_REPLIES: { [key: string]: string[] } = {
  'hallo': ['Hallo! 👋', 'Hey! Schön, dass du da bist! 😄', 'Hi! Wie geht’s dir?'],
  'hi': ['Hi! 😄', 'Hey! 👋', 'Hallo!'],
  'wie geht': ['Mir geht es gut, danke! 😊', 'Alles bestens hier! 😎', 'Super, danke der Nachfrage!'],
  'was machst du': ['Ich chatte gerade mit dir! 😄', 'Ich warte auf deine Nachricht!', 'Nichts Besonderes, nur quatschen.'],
  'hilfe': ['Wie kann ich dir helfen?', 'Was möchtest du wissen?', 'Frag mich alles, ich versuche zu antworten.'],
  'witz': ['Warum können Geister so schlecht lügen? Weil man durch sie hindurchsieht! 👻', 'Ich kenne einen guten Witz über Programmierer… 😄', 'Treffen sich zwei Planeten… keiner lacht. 😅'],
  'tschüss': ['Tschüss! Bis bald! 👋', 'Auf Wiedersehen! 😊', 'Mach’s gut!'],
  'guten morgen': ['Guten Morgen! ☀️', 'Morgen! Hoffe, du hattest einen guten Start!', 'Hallo! Schön, dass du da bist.'],
  'gute nacht': ['Gute Nacht! 🌙', 'Schlaf gut! 😴', 'Träum was Schönes!'],
  'wetter': ['Ich bin kein Wetterfrosch, aber hoffentlich scheint die Sonne!', 'Frag mich lieber nicht nach dem Wetter, ich bin drinnen. 🌤️', 'Heute scheint es Chat-warm! 😉'],
  'wie spät ist es': ['Schau auf die Uhr, ich kann leider nicht die Zeit sehen ⏰', 'Es ist immer Zeit für einen Chat! 😄'],
  'wer bist du': ['Ich bin dein Chat-Bot 🤖', 'Ich bin hier, um mit dir zu plaudern!'],
  'was kannst du': ['Ich kann auf bestimmte Nachrichten antworten 😊', 'Ich bin ein kleiner Chat-Bot, aber sehr nett!'],
  'lustig': ['Ich liebe Witze! 😄', 'Lachen ist gesund! 😂', 'Hier ein kleiner Witz für dich: …'],
  'musik': ['Ich höre gerne alles, was du mir erzählst 🎵', 'Musik ist toll! Hast du einen Lieblingssong?'],
  'essen': ['Ich esse leider nicht, aber ich liebe Rezepte! 🍕', 'Hast du Hunger? 😋'],
  'sport': ['Sport ist wichtig! 💪', 'Ich kann nicht trainieren, aber motivieren! 😄'],
  'lieblingsfarbe': ['Ich liebe blau! 💙', 'Meine Lieblingsfarbe ist digital 😉', 'Ich mag alle Farben! 🌈'],
  'reise': ['Reisen klingt toll! 🌍', 'Wo würdest du gerne hinreisen?'],
  'schule': ['Schule kann manchmal stressig sein 😅', 'Was ist dein Lieblingsfach?'],
  'arbeit': ['Arbeit hält uns beschäftigt! 💼', 'Hoffentlich hast du einen guten Tag auf der Arbeit!'],
  'film': ['Filme sind toll! 🎬', 'Welches Genre magst du am liebsten?'],
  'buch': ['Lesen ist spannend! 📚', 'Hast du ein Lieblingsbuch?'],
  'tier': ['Ich liebe Katzen 😺 und Hunde 🐶!', 'Welches Tier magst du am liebsten?'],
  'liebe': ['Liebe ist etwas Schönes ❤️', 'Ich bin nur ein Bot, aber ich schicke dir Liebe! 💌']
};
